name: CI
on:
  push:
    branches: 
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [1.21]
        os: [ubuntu-latest, windows-latest]
        make_target: [build, test]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code repository source code
      uses: actions/checkout@v2
    - name: Run ${{matrix.make_target}}
      run: |
        make ${{ matrix.make_target }}
  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.155.0
          args: release -f .goreleaser-dev.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Push development image
        run: |
          docker image tag ghcr.io/ringods/pulumi-resource:dev-amd64 ghcr.io/ringods/pulumi-resource:dev
          docker push --all-tags ghcr.io/ringods/pulumi-resource
