name: release
on:
  push:
    tags: ["v*.*.*"] # only a valid semver tag

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.155.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DOCKER_CLI_EXPERIMENTAL: enabled
